### PR TITLE
fix jenkins label and update xjsl to 0.28

### PR DESCRIPTION
**Pull request by BrennanGit**
Despite #301 being merged, it seems there were tests that only run on nightlies that saw issues we attempt to remedy here.

Apparently there is an XN file which requires the test to be run on a vrd-type board.
Also needed to fix the /projects mount path as we moved off the US agents.

examples:
- http://srv-bri-jcim0:8080/blue/organizations/jenkins/XMOS%2Fsln_voice/detail/develop/356/pipeline
- http://srv-bri-jcim0:8080/blue/organizations/jenkins/XMOS%2Fsln_voice/detail/develop/354/pipeline

Also including the xjsl version bump we've seen elsewhere. The most significant change in which is [the build discarder](https://xmosjira.atlassian.net/wiki/spaces/wiki/pages/3396534277/Build+Discarding).

### CODE REVIEW

**Comment by BrennanGit** [comment]
running once more with full test enabled as thats where we saw the issues (once merged to develop)

**Comment by BrennanGit** [comment]
ok next issue is the new jenkins agents have 2 boards attached.

dfu-utils needs one selected but we need to translate xtagid into something dfu-utils can understand.

```
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: More than one DFU capable USB device found! Try `--list' and specify the serial number or disconnect all but one device
```

**Comment by lucianomartin** [comment]
@BrennanGit, I updated this PR with the latest changes from develop. Can you check I solved the merge conflicts correctly?

**Review by lucianomartin — APPROVED** [review]
Changes look good!

**Comment by ed-xmos** [comment]
@BrennanGit any reason we shouldn't merge this?

**Comment by BrennanGit** [comment]
I wasn't sure the multiple xtags for dfu-utils had been resolved but it does seem to be passing. The PYTHON_VERSION fix is pretty crucial though.

**Comment by ed-xmos** [comment]
BTW, this fail - https://github.com/xmos/sln_voice/actions/runs/6719127858 is fixed in https://github.com/xmos/sln_voice/pull/325 which should be merged shortly

**Comment by BrennanGit** [comment]
I did a full run and it passed dfu so it's all good. By the time it finished, the base branch had been updated. Last time for sure now.

**Pull request merged**
